### ISSUE TITLE
Problems with username and password

### ISSUE THREAD

**Issue by kieuducgiang** [jacobbo/WebEye#10]
I want to play live video from this URL; but it requiried authentication.
rtsp://192.168.1.244/live0.264?user=admin&passwd=123456
Can you help me?

**Comment by rafaelkan** [comment]
Try [rtsp://admin:123456@192.168.1.244/live0.264](url)

**Comment by kieuducgiang** [comment]
Thank you Rafaelkan. My problem was solved
