### ISSUE TITLE
How to make multi thread for live CAM

### ISSUE THREAD

**Issue by jking257** [jacobbo/WebEye#11]
I have two camera and i want to start CAM1 and CAM2 with two threads
`Thread threadCam1 = new Thread(new ThreadStart(ConnectToCam1));
 threadCam1.Start();
Thread threadCam2 = new Thread(new ThreadStart(ConnectToCam2));
threadCam2.Start();
  private void ConnectToCam1()
        {
            try
            {

                if (string.IsNullOrEmpty(_cam1Setting.IPCAM))
                {
                             return;
                }
                
                string cam1URL = "";
                cam1URL = string.Format("rtsp://{0}:{1}@{2}", _cam1Setting.UIDCAM, _cam1Setting.PASSCAM, _cam1Setting.IPCAM);
                uriCAM1 = new Uri(cam1URL);
                liveCAM1.StartPlay(uriCAM1, TimeSpan.FromSeconds(15.0));

            }
            catch 
            {

            }
        }

// ConnectToCam2 is the same
`
but it fired exception Message = "Cross-thread operation not valid: Control 'liveCAM2' accessed from a thread other than the thread it was created on."

How to fix this problem?

Pls help me
Thanks you!

**Comment by jacobbo** [comment]
Hi there,

Two options:

1. Do not use threads.
2. Access the control from the thread you've created it in.

Regards,
Alexander
