### ISSUE TITLE
Not able to start camera when window is loaded

### ISSUE THREAD

**Issue by redaz808** [jacobbo/WebEye#2]
When I  start automatically the webcamdevice when the screen is loaded , I get an exception.
If I use the same code to start the camera only when I click the button, it works!

        private void InitializeComboBox()
        {
            comboBox.ItemsSource = webCameraControl.GetVideoCaptureDevices();

            if (comboBox.Items.Count > 0)
            {
                comboBox.SelectedItem = comboBox.Items[0];

                var cameraId = (WebCameraId)comboBox.SelectedItem;
                List<WebCameraId> cameras = new List<WebCameraId>(webCameraControl.GetVideoCaptureDevices());
                webCameraControl.StartCapture(cameras[0]);
            }    
        }

When the code jumps to InitializeCaptureGraph, the program crashes and I get an error "Failed to add a video capture filter"
Any idea how I can make it work?

Thanks,

**Comment by jacobbo** [comment]
Hi there,

Are you sure your screen is completely loaded? The thing is that the
control requires a created window in order to start a video stream.

Regards,
Alexander

**Comment by redaz808** [comment]
Thank you for the prompt reply!!

You are right and now it works on the loaded event.

Thank you!!
