### ISSUE TITLE
Failed to add Video Capture filter (0x80040217)

### ISSUE THREAD

**Issue by MathewSachin** [jacobbo/WebEye#27]
The control worked awesome the first time I tried it.
I used it in my screen capture program and made few videos, it worked fine.
I committed my code to git.

The next time I run my code, the moment when I call `StartCapture` method, a `COMException` is thrown.

The error code (0x80040217) is different from the similar issue: #3.

**OS**: Windows 10 Creators Update
**Stack Trace:**
```
at WebEye.Controls.Wpf.DirectShowProxy.AddCaptureFilter(String devicePath) in d:\dev\GitHub\WebEye\WebCameraControl\WPF\WebCameraControl\DirectShowProxy.cs:line 200

at WebEye.Controls.Wpf.WebCameraControl.StartCapture(WebCameraId camera) in d:\dev\GitHub\WebEye\WebCameraControl\WPF\WebCameraControl\WebCameraControl.xaml.cs:line 116

at Captura.ViewModels.WebCamViewModel.set_SelectedCamera(WebCameraId value) in F:\GitHub\Captura\src\Captura\ViewModels\WebCamViewModel.cs:line 41
```

I tested the WPF sample, it too has the same error.

I tested other apps and also the UWP Camera app, they work fine.

I think it is something to do with my system.
Have you experienced the same error?

**Comment by jacobbo** [comment]
Hi Mathew,

Please make sure that

1. your camera is not used by another app at that time

2. a control's window is visible at the time of the capture call

Regards,
Alexander

**Comment by MathewSachin** [comment]
I restarted my system 3 times and now it's working.
I'm not sure why this happened. 😢 

Anyways, thanks 👍

**Comment by MathewSachin** [comment]
I've found what is actually happening.

I have a system having an integrated as well as a dedicated graphics processor.
When I start the app on integrated graphics, everything works fine, even if the system switches to dedicated graphics for e.g. running a game.
When I start the app on dedicated graphics, fails.

The same problem seems to be happening with Desktop Duplication API, a library is DirectX.
I still have not found a way to resolve this other than starting the app on integrated graphics processor.
