### ISSUE TITLE
Memory leaks when using multiple instances of WebCameraControl.

### ISSUE THREAD

**Issue by YevgenijZ** [jacobbo/WebEye#29]
Each instance of control created in auxiliary window (like modal window/dialog for taking person photo) creates a reference to this instance inside Dispatcher.ShutdownStarted event handler.

WebCameraControl constructor - Dispatcher.ShutdownStarted += OnShutdownStarted.

This leads to entire Control - Window - ViewModel and all involved objects not being garbage collected after auxiliary window closing.

It's apparently makes sense to perform cleanup on controls Unloaded event.

**Comment by jacobbo** [comment]
I see your point, but the Unloaded event is not really reliable:
https://stackoverflow.com/questions/8908276/why-does-unloaded-event-of-window-do-not-fire-in-wpf

**Comment by YevgenijZ** [comment]
Yeah.. so you have to subscribe both ShutdownStarted and Unloaded. If Unloaded is called do clean up and remove handler from ShutdownStarted.
Anyway it was just quick idea how to fix very nasty situation - for most apps there is only one Dispatcher and it will be shut off on application exit until that moment every incarnation of WebCameraControl object will not be garbage collected as well as entire hosting dialog window with all other controls and underlying viewmodel.
ps. "_videoWindow" is not Disposed as well.

**Comment by jacobbo** [comment]
The Dispatcher.ShutdownStarted event isn't the most elegant solution, I agree.
Here is a solution which, I believe, would solve your issue:

public partial class MyCustomControl
{
    public MyCustomControl()
	{
	    InitializeComponent();

        Loaded += (sender, e)
		{
            System.Windows.Window parent = Window.GetWindow(this);
            if (parent != null)
			{
                parent.Closed += (sender2, e2)
				{
                    Dispose();
                };
            }
        };
    }
} 

This way we can get rid of the ShutdownStarted event.

**Comment by YevgenijZ** [comment]
Looks good for me, really appreciate your work, will be great to have such fix for next versions.

I temporally fixed inside my project by hooking into unloaded event (it's called always except main window closing but there disposal goes backed by Dispatcher.ShutdownStarted), but better have proper version without reflection and use one handler Window.Closed as you posted. Thanks.
```
        static void OnCameraControlUnloaded(object sender, RoutedEventArgs e)
        {
            var cameraControl = (WebCameraControl)sender;
            cameraControl.Unloaded -= OnCameraControlUnloaded;

            var onShutdownStarted = (EventHandler)cameraControl.GetType()
                                                               .GetMethod("OnShutdownStarted", BindingFlags.NonPublic | BindingFlags.Instance)
                                                               ?.CreateDelegate(typeof(EventHandler), cameraControl);
            if (onShutdownStarted == null)
                return;
            
            cameraControl.Dispatcher.ShutdownStarted -= onShutdownStarted;
            onShutdownStarted(cameraControl.Dispatcher, EventArgs.Empty);

            var videoWindow = (HwndHost)cameraControl.GetType().GetField("_videoWindow", BindingFlags.NonPublic | BindingFlags.Instance)?.GetValue(cameraControl);
            videoWindow?.Dispose();
        }
```

**Comment by jacobbo** [comment]
I've committed the fix and updated the nuget package.

**Comment by YevgenijZ** [comment]
I took latest nuget package and it's ok now for my scenario. thx.
