### ISSUE TITLE
Provide an option to force RTSP on TCP instead of UDP (default)

### ISSUE THREAD

**Issue by KodeKooker** [jacobbo/WebEye#30]
FFmpeg tries first using UDP transport layer, and in case of failure it uses TCP. But due to a bug, during this switch it fails to retrieve the stream properties and fails. The problem is that some IP Cameras are configured only for TCP protocol and don't/can't support UDP, depending on the specific application context.

With the command line command we can use the FFmpeg option "rtsp_transport tcp" to force TCP from the start, so I think this option should be available in your library also (without needing to search for the original libraries and trying to recompile the bottom layer C++ project).

**Comment by jacobbo** [comment]
I've added an option to set a transport protocol:
`streamPlayerControl1.StartPlay(new Uri("rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov"),
    TimeSpan.FromSeconds(15), RtspTransport.UdpMulticast);`
