### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by xperseguers** [jacobbo/WebEye#34]
Deploying an app using the webcam control works on some computers but fails on others:

```
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.AccessViolationException
   à WebEye.Controls.Wpf.DirectShowProxy.AddCaptureFilter(System.String)
   à WebEye.Controls.Wpf.WebCameraControl.StartCapture(WebEye.Controls.Wpf.WebCameraId)
   à System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   à System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   à System.Windows.Controls.ComboBox.OnSelectionChanged(System.Windows.Controls.SelectionChangedEventArgs)
```

Any idea what could be the cause of this access violation exception?

I thought maybe the privacy settings of Windows 10 prevents my app to access the webcam. Since my app was not listed under Settings > Privacy > Camera, I went to `gpedit.msc` and explicitly asked to allow any app to access the camera. It does not help.

App is running in 64 bit.

**Comment by jacobbo** [comment]
Are you using the latest nuget package (1.0.3)?

**Comment by xperseguers** [comment]
I'm using the project and I compiled the DLL on my own (somehow did not see the nuget package). I can try to use the official release.

**Comment by jacobbo** [comment]
Try this one([Debug.zip](https://github.com/jacobbo/WebEye/files/1446393/Debug.zip)), that's the latest official.

**Comment by xperseguers** [comment]
Test program from Debug.zip works on the machine where it crashes with my app.

I tried to load the DLL from NuGet but cannot compile my code since:

```
Could not load file or assembly 'WebEye.Controls.Wpf.WebCameraControl, Version=1.0.0.0,
Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-name assembly
is required.
```

In fact, my assembly is signed and thus requires every referenced assemblies to be signed as well. It works if I recompile the DLL from source code and sign it myself with my own private key.

**Comment by jacobbo** [comment]
Make sure you have the latest changes - do a pull and rebuild the sources.

**Comment by xperseguers** [comment]
ok, recompiling from sources and running the demo app works. will further investigate to figure out why it then crashes when used "for real" in my app.

**Comment by xperseguers** [comment]
Just don't get it, I basically removed "everything" in my main window to just have the content of the demo app and it crashes as well, same error. Only difference I see is having more references to various libraries. really weird but something to investigate on my own then.
