### ISSUE TITLE
StreamPlayer is not building correctly

### ISSUE THREAD

**Issue by SMUsamaShah** [jacobbo/WebEye#35]
OS: Windows 7
IDE: Visual Studio 2017
Windows SDK Version: 7.0
Platform Toolset: Visual Studio 2017 - Windows XP (v141_xp)

I have added **StreamPlayer** and **StreamPlayerControl** projects to **StreamPlayerDemo** solution. 

In StreamPlayerProxy.cs I changed the load library to `_hDll = LoadLibrary("D:\WebEye-master\StreamPlayerControl\StreamPlayer\Debug\StreamPlayer.dll");` so that the DLL I compiled is loaded instead of StreamPlayer.dll from StreamControlPlayer resources.

Now when I run and press play I get 

> The procedure entry point av_sterror could not be located in the dynamic link library avformat-58.dll

on `LoadLibrary(...)`

StreamPlayer.dll which I build is only 1.25MB while StreamPlayer.dll bundled as a resource is 12.5MB. Is that the problem? How to correctly build it?

**Comment by jacobbo** [comment]
Yes, StreamPlayer.dll depends on FFmpeg and boost libs and you will need to link them statically (as opposed to shared linking). Here are the building instructions for the C++ part: https://github.com/jacobbo/WebEye/issues/33#issuecomment-339588078
