### ISSUE TITLE
WPF sample crashes if url not valid 

### ISSUE THREAD

**Issue by diegocvazquez** [jacobbo/WebEye#38]
Hello,
First of all thank you very much for this amazing control. I have been testing your WPF samples and when I try to start streaming using a wrong url, the application closes abruptly. I have tried to „try catch” the exception in several way but without any success. Do you have any suggestions for a work around?
Thank you in advanced for your help.
Regards, 
Diego

**Comment by jacobbo** [comment]
Hi Diego,

Thanks for your feedback. Could you please provide an example of such a url?

Regards,
Alexander

**Comment by diegocvazquez** [comment]
Hi! 
Thank you for your fast response, If I use this url for example

1.
http://wmccpinetop.axiscam.net/axis-media/media.amp 
The sample crashes. There is no stream serice in that url.

2. 
http://wmccpinetop.axiscam.net/mjpg/video.mjpg
That works.

3.
http://wmccpinetop.axiscam.net/mjpg/video.mjpgx
that url does not exist (404) that is crashing the sample at least in my case

Thank you very much, regards,
Diego

**Comment by jacobbo** [comment]
Please have a look at the demo app, it handles all three urls correctly.
https://www.codeproject.com/KB/audio-video/885869/Working/WpfDemo.zip

Demo app's source is available here:
https://www.codeproject.com/KB/audio-video/885869/WpfSource.zip

Regards,
Alexander

**Comment by diegocvazquez** [comment]
Hi Alexander, 
I have tried the codeproject version and yes!, you are right, it works!!!

I was doing all the testing using the github version there are also some WPF samples, but with the codeproject version works like charm, I get and error message when the url is not right, thats greate, thank you very much for you time and help.

Kind regards,
Diego
