### ISSUE TITLE
Did streamPlayerControl support play local video files

### ISSUE THREAD

**Issue by xhhha123** [jacobbo/WebEye#4]
Hi all,

I have download your demo and code sources. It work greate in my local pc.

But I have confused that is that your streamPlayerControl support play local video files. I noticed that it only support play the uri video in method StartPlay();

Best Regards,
Richard

**Comment by jacobbo** [comment]
Hi there,

Good point. I will add support for local files playback.

Regards,
Alexander

**Comment by xhhha123** [comment]
Hi Alexander,

Thanks for your reply. Would it be hard to support for local files playback? And how long it will take?

Because we have a project needs this feature recently and we want to use your great demo as our part.

Regards,
Richard

**Comment by jacobbo** [comment]
Hi Richard,

I will try to deliver it by the end of the week.

Regards,
Alexander

**Comment by xhhha123** [comment]
Hi Alexander,

Thanks a lot. Waiting for your good news.

Regards,
Richard

**Comment by jacobbo** [comment]
Hi Richard,

I have committed my changes for local files playback. Now you can supply a local path as an input:

var uri = new Uri(@"c:\files\video.mp4");
_streamPlayerControl.StartPlay(uri);

You can download the control's sources here and build them or download the built version from codeproject.com:
http://www.codeproject.com/Articles/885869/Stream-Player-control

Thanks for your feedback!
Alexander

**Comment by xhhha** [comment]
Hi Alexander,

Thanks for your update. I have downloaded the latest winform demo but it seems not work.

I was playing these local video but if failed. Please rename the attached files as rar files(Github not allowed to upload the rar file so I have renamed it. It is not the virus files). Could you please help me? 

BTW, how much video format type (such as AVI, MPG, FLV) does your demo support for?

Regards,
Richard

![wildlife avi to mp4](https://cloud.githubusercontent.com/assets/6767647/11025606/2659ffee-86d8-11e5-9730-cb46376b8a16.png)

**Comment by jacobbo** [comment]
Hi Richard,

Sorry, I do not see your file, just a broken image. You could upload it somewhere and add the link in a comment. You can use gist for this: https://gist.github.com

Regarding format types, the control uses FFmpeg library as a back-end engine and FFmpeg supports many of them, the formats you mentioned are supported.

Regards,
Alexander

**Comment by xhhha** [comment]
Hi Alexander,

Sorry for that. You can visit these file with https://drive.google.com/file/d/0BxGMleff3St8aGJEYk5zSlRNdEU/view?usp=sharing

Regards,
Richard

**Comment by jacobbo** [comment]
Hi Richard,

I have updated the demo, please try again.

Regards,
Alexander
