### ISSUE TITLE
Other WPF controls are unable to overlay StreamPlayerControl

### ISSUE THREAD

**Issue by vzhadeyev** [jacobbo/WebEye#41]
Is there a way to place other controls over StreamPlayerControl? No matter which ZIndex property is set, stream overwrites them (is that a problem of using hWnd pointer of a parent window to draw frames?).

**Comment by jacobbo** [comment]
No, sorry, the current implementation doesn't support this. The reason you mentioned is correct.

**Comment by vzhadeyev** [comment]
Find a general [solution](https://github.com/michaelsutton/hwnd-adorner) to add elements over hwnd hosted by an HwndHost. For now, checked only TextBlock
![image](https://user-images.githubusercontent.com/15178388/35480157-bcad2668-0432-11e8-9097-85367e14f5d2.png)

**Comment by jacobbo** [comment]
Cool! Do you have to change the control to achieve this behavior?

**Comment by vzhadeyev** [comment]
Only a little bit. VideoWindow should be packed into HwndHostPresenter (helper class from mentioned solution). HwndHostPresenter can be used as control which Adornment property is your overalaying UI elements. I had no time to dive deep into solution, may be its author can provide more information.
But your project is very lightweight solution which helped to drop memory usage per single stream from 30Mb with VLC to 3-5Mb with WebEye. Waiting for improvements!
