### ISSUE TITLE
Memory leak when using GetCurrentFrame 

### ISSUE THREAD

**Issue by aganemnam** [jacobbo/WebEye#68]
My Application growth on ram when i use GetCurrentFrame  in timer.
How i can get frames (Bitmap\png) as soon as posible with no lags and memory leaks ?

**Comment by jacobbo** [comment]
Can you run this project and see if ram is increasing?
https://drive.google.com/file/d/1LuZ5uIKYDfXNUM35STIbUlzxMFP8qhhp/view?usp=sharing

**Comment by aganemnam** [comment]
it ist open.
But i prepare solution test you can see how memory encreeses when it works
https://drive.google.com/open?id=1LuZ5uIKYDfXNUM35STIbUlzxMFP8qhhp

**Comment by aganemnam** [comment]
@jacobbo  Any Issue ?

**Comment by jacobbo** [comment]
Sorry, did you send me something? Your last link pointing to my zip file.
Make sure you dispose images you get from GetCurrentFrame.

**Comment by aganemnam** [comment]
Issue can be closed. Updated version 1.0.6.0 which located on Nuget ( autored by rymkin) hasn`t such memory leak. Just update from that source
