### ISSUE TITLE
AllowsTransparency=true causes WebCameraControl to not render video

### ISSUE THREAD

**Issue by DrainSmith** [jacobbo/WebEye#9]
In WPF if AllowsTransparency=true on a Window then the WebCameraControl doesn't render the video. The webcam is still open and images can still be captured from it.

**Comment by jacobbo** [comment]
Thanks for your feedback. The control uses the HwndHost control which is not supported by WPF transparent windows. More details and workaround can be found [here](http://stackoverflow.com/questions/4108531/wpf-windowsformshost-is-not-visible-when-allowstransparency-true).
